# -*- mode: python ; coding: utf-8 -*-
"""PyInstaller onedir 规格：产出 dist/easyword/easyword.exe

请在项目 .venv 中执行（见 scripts/build_sidecar.ps1），勿在 qhub_v1 等重型环境打包。
"""

# 仅列运行 sidecar 必需的 hiddenimports，避免 collect_submodules 拉入 testclient 等可选模块
hidden = [
    "word",
    "word.app",
    "word.router",
    "word.config",
    "word.config.constants",
    "word.config.settings",
    "word.core",
    "word.core.health",
    "word.core.health.router",
    "word.core.health.router.health",
    "word.core.health.schema",
    "word.core.health.schema.health",
    "word.core.document",
    "word.core.document.router",
    "word.core.document.router.document",
    "word.core.document.schema",
    "word.core.document.schema.document",
    "word.core.document.service",
    "word.core.content_control",
    "word.core.content_control.constants",
    "word.core.content_control.selection_guard",
    "word.core.content_control.service",
    "word.core.content_control.router",
    "word.core.content_control.router.content_control",
    "word.core.content_control.schema",
    "word.core.content_control.schema.content_control",
    "word.runtime",
    "word.runtime.com_host",
    "word.runtime.word_app",
    "word.runtime.document_binding",
    "word.runtime.errors",
    "word.runtime.paths",
    "pythoncom",
    "pywintypes",
    "win32com",
    "win32com.client",
    "win32api",
    "win32event",
    "uvicorn.logging",
    "uvicorn.loops",
    "uvicorn.loops.auto",
    "uvicorn.protocols",
    "uvicorn.protocols.http",
    "uvicorn.protocols.http.auto",
    "uvicorn.protocols.websockets",
    "uvicorn.protocols.websockets.auto",
    "uvicorn.lifespan",
    "uvicorn.lifespan.on",
    "anyio._backends._asyncio",
]

excludes = [
    "pandas",
    "numpy",
    "pyarrow",
    "matplotlib",
    "scipy",
    "sklearn",
    "torch",
    "tensorflow",
    "nltk",
    "sympy",
    "IPython",
    "jupyter",
    "notebook",
    "tkinter",
    "PySide2",
    "PySide6",
    "PyQt5",
    "PyQt6",
    "sqlalchemy",
    "pymongo",
    "psycopg2",
    "psycopg",
    "openpyxl",
    "pyreadstat",
    "pytest",
    "passlib",
    "jwt",
    "typer",
    "rich",
    "langchain",
    "langchain_classic",
    "spacy",
    "thinc",
    "playwright",
    "boto3",
    "botocore",
    "grpc",
    "pdfminer",
    "pypdfium2",
    "docx",
    "pptx",
    "msoffcrypto",
    "magic",
    "langdetect",
    "emoji",
    "nbformat",
    "jsonschema",
    "traitlets",
    "orjson",
    "sentry_sdk",
]

a = Analysis(
    ["word/__main__.py"],
    pathex=["."],
    binaries=[],
    datas=[],
    hiddenimports=hidden,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=excludes,
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name="easyword",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name="easyword",
)
